-- ============================================================
-- Migration 007 — Category confirmation tracking
-- (one-time, run once against an existing production database;
-- the objects this creates are already part of supabase/schema.sql
-- for fresh installs)
--
-- Adds category_confirmed_at to transactions: NULL means "the system
-- auto-categorized and auto-approved this without human review, and the
-- user hasn't confirmed the category yet." Every other transaction (manual
-- entries, anything the user explicitly approved via Pending Alerts) has
-- a timestamp here, since those never needed a silent-auto-approval
-- confirmation in the first place.
--
-- Existing rows are automatically backfilled with the current timestamp
-- by ADD COLUMN's own DEFAULT clause — no separate UPDATE needed. This is
-- deliberate: a separate backfill UPDATE would be unsafe to accidentally
-- re-run after go-live, since it would silently mass-confirm any
-- transaction genuinely awaiting the user's review.
-- ============================================================

ALTER TABLE public.transactions ADD COLUMN IF NOT EXISTS category_confirmed_at TIMESTAMPTZ DEFAULT now();
